package com.rana.event_contracts;

public enum SagaStatus {
    STARTED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    INVENTORY_PENDING,
    INVENTORY_COMPLETED,
    INVENTORY_FAILED,
    COMPLETED,
    COMPENSATING,
    COMPENSATED,
    FAILED
}
